### ISSUE TITLE
Console still has dark theme

### ISSUE THREAD

**Issue by funcJeff** [nelsyeung/Solarized-Light-for-Xcode#1]
While the Source Editor has light colors with this theme, the Console colors are still the darker ones.

![image](https://user-images.githubusercontent.com/2448801/55252951-07847e00-5222-11e9-90c6-b2b77231f69d.png)

**Comment by nelsyeung** [comment]
Sorry for the late reply, I didn't see the notification. I just pushed the fix, let me know if there're any problems.
